<a href="https://colab.research.google.com/github/toweliewang/DL/blob/master/D2_GRNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install neupy

     |████████████████████████████████| 235kB 2.8MB/s 
     |████████████████████████████████| 92.6MB 365kB/s 
     |████████████████████████████████| 3.2MB 26.7MB/s 
     |████████████████████████████████| 368kB 48.3MB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1
  Found existing installation: progressbar2 3.38.0
    Uninstalling progressbar2-3.38.0:
      Successfully uninstalled progressbar2-3.38.0
  Found existing installation: tensorboard 1.14.0
    Uninstalling tensorboard-1.14.0:
      Successfully uninstalled tensorboard-1.14.0
  Found existing installation: tensorflow-estimator 1.14.0
    Uninstalling tensorflow-estimator-1.14.0:
      Successfully uninstalled tensorflow-estimator-1.14.0
  Found existing installation: tensorflow 1.14.0
    Uninstalling tensorflow-1.14.0:
      Successfully uninstalled tensorflow-1.14.0


In [0]:
import numpy as np
from sklearn import datasets, preprocessing
from sklearn.model_selection import train_test_split
from neupy import algorithms

In [0]:
dataset = datasets.load_diabetes()

In [5]:
dataset.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [6]:
dataset.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [0]:
x_train, x_test, y_train, y_test = train_test_split(
    preprocessing.minmax_scale(dataset.data),
    preprocessing.minmax_scale(dataset.target.reshape(-1, 1)),
    test_size=0.3,random_state=42
)

In [8]:
y_train

array([[0.57009346],
       [0.73520249],
       [0.47975078],
       [0.7258567 ],
       [0.73831776],
       [0.08099688],
       [0.66043614],
       [0.14330218],
       [0.35514019],
       [0.75700935],
       [0.13707165],
       [0.90965732],
       [0.69781931],
       [0.40186916],
       [0.52024922],
       [0.2834891 ],
       [0.17445483],
       [0.30218069],
       [0.72897196],
       [0.51713396],
       [0.8317757 ],
       [0.09345794],
       [0.25545171],
       [0.57632399],
       [0.20560748],
       [0.71028037],
       [0.18691589],
       [0.70716511],
       [0.105919  ],
       [0.16510903],
       [0.54517134],
       [0.16510903],
       [0.68535826],
       [0.46728972],
       [0.0529595 ],
       [0.31775701],
       [0.08722741],
       [0.21495327],
       [0.24610592],
       [0.54205607],
       [0.74766355],
       [0.79750779],
       [0.69470405],
       [0.72274143],
       [0.59190031],
       [0.86604361],
       [0.4517134 ],
       [0.105

In [0]:
grnn = algorithms.GRNN(std=0.1, verbose=False)
grnn.train(x_train, y_train)

In [0]:
y_predicted = grnn.predict(x_test)

In [11]:
y_predicted

array([[0.62410371],
       [0.36997427],
       [0.43451023],
       [0.63062104],
       [0.18353818],
       [0.27011462],
       [0.65010106],
       [0.35648378],
       [0.24610342],
       [0.14703394],
       [0.10903761],
       [0.47810057],
       [0.25153746],
       [0.83160737],
       [0.15620775],
       [0.44736162],
       [0.84507261],
       [0.62595479],
       [0.7052235 ],
       [0.72099333],
       [0.23073269],
       [0.17748745],
       [0.2179901 ],
       [0.5005631 ],
       [0.38057724],
       [0.35694173],
       [0.41669934],
       [0.25222545],
       [0.11986704],
       [0.3817577 ],
       [0.36916871],
       [0.35500378],
       [0.19270356],
       [0.52133766],
       [0.41264062],
       [0.55781571],
       [0.14493699],
       [0.17161703],
       [0.7795792 ],
       [0.16974266],
       [0.1286181 ],
       [0.14542837],
       [0.59858832],
       [0.21713542],
       [0.55890431],
       [0.17162684],
       [0.13742512],
       [0.127

In [12]:
mse = np.mean((y_predicted - y_test) ** 2)
mse

0.042288300975670025